### PR TITLE
Add License GNU AGPL v3

### PR DESCRIPTION
**Pull request by superherointj**
@harshavardhana

~(I assume) Same license as:~
~https://github.com/minio/minio/blob/master/LICENSE~

This is important for packaging the project. (I want to package it for Nixpkgs.)

### CODE REVIEW

**Comment by harshavardhana** [comment]
This is not an AGPL licensed project closing.

**Comment by superherointj** [comment]
Add a license then. That was the point of it.

**Comment by superherointj** [comment]
This project is being recommended on Minio website. But it's license is not clear.

**Comment by harshavardhana** [comment]
> Add a license then. That was the point of it.

The license header is available as part of the source code

**Comment by superherointj** [comment]
> > Add a license then. That was the point of it.
> 
> The license header is available as part of the source code

I'm sorry. Wasn't aware. Still, would be nice to define the license file as usual in GitHub.
```
// Copyright 2009 The Go Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.
```
It references a LICENSE file as well.

**Comment by superherointj** [comment]
https://golang.org/LICENSE

Is this the license?

**Pull request closed without merging**
